### ISSUE TITLE
Requires containers ergo cannot be used on MacOS image

### ISSUE THREAD

**Issue by TimothyChilvers** [AutoModality/action-xunit-viewer#2]
I have an iOS project running on a MacOS image hosted by Github. It does not support containers. Is there any way to remove the requirement of containers?
An example of my yml:
```
jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Convert JUnit to HTML
      if: always()
      id: xunit-viewer
      uses: AutoModality/action-xunit-viewer@v1.0.1
      with:
        results: fastlane/test_output/TestResults.xml
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test report
        path: ${{ steps.xunit-viewer.outputs.report-dir }}
```
Expected: A glorious HTML test report
Actual result:
```
1
Run AutoModality/action-xunit-viewer@v1.0.1
2
  with:
3
    results: fastlane/test_output/TestResults.xml
4
##[error]Container action is only supported on Linux
```
